### ISSUE TITLE
Create new virtual machine offer

### ISSUE THREAD

**Issue by alexandrakoller** [microsoft/az-partner-center-cli#82]
The current `azpc vm create` CLI command fails as it tries to use the Partner Portal API instead of the Cloud Partner Portal API. It appears to be due to the creation method not yet built into the virtual_machine.py class.

**Comment by dciborow** [comment]
This one surprises me, because this command is one of the critical ones for my internal processes. I will investigate further, and wonder if "azpc vm update" is working as intended?

**Comment by alexandrakoller** [comment]
> This one surprises me, because this command is one of the critical ones for my internal processes. I will investigate further, and wonder if "azpc vm update" is working as intended?
 `azpc vm update` is working as expected. We have forked this repo and added in some changes to get this working. We can discuss this tomorrow in our call.
But essentially, the `create()` method was missing from the virtual_machine.py class, so it was using the `create()` method from the parent class, which is using the wrong API. We have added in the method (and more testing) in our fork.
