### ISSUE TITLE
Create plans on offer creation

### ISSUE THREAD

**Issue by alexandrakoller** [microsoft/az-partner-center-cli#84]
When an offer is created for solution template and managed application offers (potentially others), the offer is created, some configurations are set, however the plans are not currently being created.
As a user, when a configuration file that contains a list of plans are included, it would be expected that all configurations are set including the creation of the plans.

**Comment by dciborow** [comment]
The current usage pattern expected would be for the app to be created and then the plan to be created. Currently a configuration file can contain only a single plan. (this is not really an intended design, but was not initially considered)

```shell
azpc ma create --name MyApp
azpc ma create plan --name MyApp --plan-name MyPlan
```


The proposal here is to initially create all of the objects in a configuration file using the single command

```shell
azpc app create --name MyApp
```

Where each plan with the configuration is created. This will require a new configuration field to be added to a plan, to specific if it is a managed app or solution template (or both).

Then, if a user adds a new plan in the future, it would be added with the following command.
```shell
azpc app update --name MyApp
```
